pageEngine
    .init('.wrapper')
        .addSection('page1')
            .addComponent(bgConfig)
                .addComponent(bg11Config)
                    .addComponent(bg12Config)
                        .addComponent(bg13Config)
                            .addComponent(hgroup)
                                .addComponent(p11)
        .addSection('page2')
            .addComponent(bg2Config)
                .addComponent(bg21Config)
                    .addComponent(bg22Config)
                        .addComponent(bg23Config)
                            .addComponent(h1Config)
                                .addComponent(h2Config)
                                    .addComponent(p3Config)
        .addSection('page3')
            .addComponent(bg3Config)
                .addComponent(bg31Config)
                    .addComponent(bg32Config)
                        .addComponent(bg33Config)
                            .addComponent(P3h1Config)
                                .addComponent(P3h2Config)
                                    .addComponent(P3h3Config)
        .addSection('page4')
            .addComponent(bg4Config)
                .addComponent(bg41config)
                    .addComponent(bg42config)
                        .addComponent(bg43config)
                            .addComponent(P4h1Config)
                                .addComponent(P4h2Config)
                                    .addComponent(P4h3Config)
        .bindEvent()
            .load()



